# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_basic_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.TextField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_extra_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('website_link', models.CharField(blank=True, max_length=40, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
