# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extra_detail',
            name='profession',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
