# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_user_extra_detail_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('interests', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='life_events_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('life_events', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='places_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('places', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='working_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('workplace', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
