# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_interest_detail_life_events_detail_places_detail_working_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interest_detail',
        ),
        migrations.DeleteModel(
            name='life_events_detail',
        ),
        migrations.DeleteModel(
            name='places_detail',
        ),
    ]
